version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: python3 tests/basic.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev